import Head from "next/head";
import styled from "styled-components";
import Sidebar from "../components/Sidebar";

const StyledContainer = styled.div`
  display: block;
`;

export default function Home() {
  return (
    <StyledContainer>
      <Head>
        <title>Chat app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
    </StyledContainer>
  );
}
